# Window Customization
window:
  dimensions:
    columns: 150
    lines: 40
  padding:
    x: 15
    y: 15
    #  decorations: none
  dynamic_title: true
scrolling:
  history: 10000
  multiplier: 3
  #background_opacity: .8

# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: false

# Font Customization
font:
  normal:
    family: UbuntuMono Nerd Font Mono
    style: Bold
  bold:
    family: UbuntuMono Nerd Font Mono
    style: Bold
  italic:
    family: UbuntuMono Nerd Font Mono
    style: Italic
  size: 14
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

# Color Settings (nord)


# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: 28,      mods: Alt, chars: "{" }
  - { key: 25,      mods: Alt, chars: "}" }
  - { key: 37,      mods: Alt, chars: "@" }
  - { key: 26,      mods: Alt|Shift, chars: "\\" }
  - { key: 26,      mods: Alt, chars: "|" }
  - { key: N,       mods: Alt|Shift, chars: "\x7E" }
    #- { key: N,       mods: Alt, chars: "~" }
  - { key: 23,      mods: Alt, chars: "[" }
  - { key: 22,      mods: Alt, chars: "]" }
  - { key: 36,      mods: Command, action: ToggleFullscreen }
  - { key: W,       mods: Command, action: None             }
  - { key: Q,       mods: Command, action: None             }

